app:
  port: 8000
  host: "0.0.0.0"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  name: "newsletter"
email:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  auth_token: "secret"
  timeout_ms: 10000
